import Head from "next/head";
import About from "../components/About";
import Main from "../components/Main";
import Navbar from "../components/Navbar";
import Projects from "../components/Projects";
import Diplome from "../components/Diplome";
import Veille from "../components/Veille";

export default function Home() {
  return (
    <div>
      <Head>
        <title>Ruben Gallien BTS SIO</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Main />
      <About />
      <Projects />
      <Veille />
      <Diplome />
    </div>
  );
}
